### ISSUE TITLE
Missing output directory

### ISSUE THREAD

**Issue by brn7331** [shadowlabscc/Kaiten#3]
Hi guys,

Great work!
deleting the file from the output directory deleted the directory itself from git cause its empty, which is needed for the code to work, I would suggest to make the python create it if it's missing, or use gitignore to make it stay (https://stackoverflow.com/questions/115983/how-can-i-add-an-empty-directory-to-a-git-repository)

**Comment by shadowlabx** [comment]
Thanks brn7331 for your interest in kaiten! we have just fixed it. let us know if any problems happen again.
