### ISSUE TITLE
Install??

### ISSUE THREAD

**Issue by n01root** [shadowlabscc/Kaiten#5]
Hello, how do I install this package?? there's no setup.py

**Comment by ctoslab** [comment]
Hi, just install those requirements 

sudo apt-get install gcc
sudo apt-get install osslsigncode
sudo apt-get install mingw-w64

Download the tool
git clone https://github.com/shadowlabscc/Kaiten.git
cd Kaiten && chmod 777 main.py

After that just run main.py make sur that you have installed python3 not other version. hope this helps
